### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by dannyvankooten** [Gaya/MarkPress#1]
```
Put 192.168.56.125 markdown.dev in your hosts file
Go to http://markpress.dev in your browser
```

I followed the instructions but when I go to http://markpress.dev I get an error telling me "This webpage is unavailable."

Any ideas?

**Comment by dannyvankooten** [comment]
Grapje. Maar typo'tje dus. ;)

**Comment by Gaya** [comment]
Hahahah oh shit! Thanks

**Comment by Gaya** [comment]
https://github.com/Gaya/MarkPress/commit/de1703794e72827eeddb0759f48a88ca615c6495
